#! /bin/bash

# stop script when an error occurs
set -e

psql -q -c "CREATE USER jess SUPERUSER PASSWORD '123'"
echo "Created Postgres user 'jess'"

psql -q -c "CREATE DATABASE week7db WITH OWNER jess"
echo "Created Postgres database 'week7db'"

cp -r example.env .env
echo "Created .env containing DATABASE_URL"